### ISSUE TITLE
Code gets people out of his car

### ISSUE THREAD

**Issue by alejandro2016** [AlternateLife/JustAnotherVoiceChat#17]
And stop his animation while walking, actually any animation.
 NAPI.Player.StopPlayerAnimation(speakingClient.Player);

Had to remove it and workaround

**Comment by Micky5991** [comment]
This is a known issue, because the Bridge uses a task clear method to stop normal animations, but this also cancels the task to drive a vehicle. 

The only way to solve this, is to overwrite it with a different animation, or implement a custom solution. The resource `JustAnotherVoiceChat.Server.RageMP.Resource` is only a demonstration.

**Comment by searusu** [comment]
just change that line in resource to:
`NAPI.Player.PlayPlayerAnimation(speakingClient.Player, (int)(0 | AnimationFlag.AllowRotation), "mp_facial", "mic_chatter");`
By that you will fix "clear method" without any notable impact in visual effects ingame.
